Funcionalidad del módulo de alumno
sebasx200/Clase_8 pull request #1
Opened 2023-05-01 23:23 UTC by sebasx200-1

Permite ingresar el nombre y tres notas de cada alumno 
Pregunta si desea ingresar otro alumno, calcula el promedio de cada alumno
Muestra en forma tabular los datos de cada alumno, los promedios

2023-05-01 23:37 UTC, sebasx200 reviewed
Hacer la funcionalidad para que muestre en forma tabular los alumnos que perdieron

2023-05-01 23:37 UTC, sebasx200 commented on alumnos.py
> +
Hacer la funcionalidad para que muestre en forma tabular los alumnos que perdieron

2023-05-01 23:38 UTC, sebasx200 requested changes
Hacer la funcionalidad para que muestre en forma tabular los alumnos que perdieron

2023-05-01 23:55 UTC, sebasx200-1 commented
Se agrega la funcionalidad que muestra la lista de estudiantes que perdieron la materia. Quedo pendiente de la revisión.

2023-05-01 23:59 UTC, sebasx200 approved these changes
Listo, todo completo, muchas gracias

2023-05-02 00:52 UTC, merged

2023-05-02 00:56 UTC, sebasx200 commented
Se hace el merge de alumnos con develop